server:
  port: 8000
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS}|%level|%logger.%M|%X{uuid}|%X{uri}|%X{method}|%msg%n"
